name: Build and Test Parallel Solver on Linux and Mac OS

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install zlib1g-dev make cmake picosat

    - uses: actions/checkout@v1

    - name: mergesat build
      run: make BUILD_TYPE=parallel d r p sh lr ld lp lsh

    - name: run CI script
      env:
        RUNOPENWBO: 0
        RUNFUZZ: 0
        RUNDIVERSIFY: 0
      run: ./tools/ci.sh

#    Needs Mac OS rework on the linking
#  MacOS:
#
#    runs-on: macos-latest
#
#    steps:
#    - name: Install Packages
#      run: brew install libzip
#
#    - uses: actions/checkout@v1
#
#    - name: mergesat library build
#      run: make BUILD_TYPE=parallel sh lr ld lsh
#
#    - name: mergesat binary build
#      run: make BUILD_TYPE=parallel d r
